[package]
name = "std-1rpc"
version = "1.0.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
glog = { git = "https://github.com/automata-network/glog-rs" }
apps = { path = "../../../src/apps" }
app-1rpc = { path = "../../../src/apps/1rpc" }
